name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Berjalan otomatis setiap tengah malam UTC
  workflow_dispatch:    # Memungkinkan trigger manual dari tab Actions di GitHub
  push:
    branches:
      - main            # Berjalan otomatis setiap kali ada push ke branch main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Generate the snake files
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
